export enum commonResponseMessage {
  SOMETHING_WENT_WRONG = 'Something went wrong!',
  INVALID_CREDS = 'Invalid Credentials!',
  SUCCESS = 'Success!',
  FAILED = 'Failed!',
  LOGIN_SUCCESS = 'Login Successfully',
  SIGNUP_SUCCESS = 'Sign Up Successfully',
  SIGNUP_FAILED = 'Sign Up Failed!',
  LOGIN_FAILED = 'Login Failed!',
  OTP_SENT = 'OTP sent!',
  USER_ALREADY_EXIST = 'User already exist!',
  USER_NOT_EXIST = 'User not exist!',
  UNVERIFED_USER_DELETE_SUCCESS = 'Unverifed User deleted successfully!',
  UNVERIFED_USER_DELETE_FAIL = 'Unverified User deleted Failed!',
}
